name: ESLint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "17 23 * * 4"
  workflow_dispatch:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint and SARIF formatter
        run: |
          npm install
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint and generate SARIF
        id: lint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . --config eslint.config.mjs \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif || echo "eslint_failed=true" >> $GITHUB_OUTPUT

      - name: Print ESLint errors (human-readable)
        run: npx eslint . --config eslint.config.mjs --format stylish || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif

      - name: Fail if ESLint had errors
        if: steps.lint.outputs.eslint_failed == 'true'
        run: exit 1
